### PR TITLE
Msg Format conflict fix

### LINKED ISSUE #161: unable to use CliFormat to override ConfigFormat
https://github.com/projectdiscovery/notify/blob/c9f7cc3025f5e400aeabd821686377c2d796cbf7/pkg/utils/utils.go#L25

If `ConfigFormat` for a given provider is `testing {{data}}` and, using the cli flag, I try to override with `{{data}}` (aka defaultFormat), it will be ignored.

Is there any reason for that condition or could it be removed?

### PR DESCRIPTION
**Pull request by parrasajad**
closes #161

### CODE REVIEW

File: pkg/utils/utils.go [hunk 1]
```diff
@@ -1,30 +1,27 @@
...
 	return strings.Replace(format, defaultFormat, msg, -1)
 }
 
+// SelectFormat returns the format string in the following order of precedence:
+// 1. cliFormat
+// 2. configFormat
+// 3. defaulFormat
 func SelectFormat(cliFormat, configFormat string) string {
-	if cliFormat != "" && cliFormat != defaultFormat {
+	fmt.Println("cliFormat: ", cliFormat)
```
Comment (Mzack9999) [inline pkg/utils/utils.go:20]: Please remove debug instructions

**Review by Mzack9999 — CHANGES_REQUESTED** [review]

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]
