### PR TITLE
fix proxy setting when ratelimit is 0

### LINKED ISSUE #403: proxy not working when ratelimit is 0
### Current Behavior:
Telegram doesn't receive messages when using proxy and rate limit set to 0.

### Expected Behavior:
Telegram can receive messages when using proxy and rate limit set to 0.

### Steps To Reproduce:
```
echo yes | notify -proxy http://127.0.0.1:8080 -rl 0 -v
```
```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by AaronChen0**
Fix #403 

Changes I make:
1. `defaultTransport` should be used when ratelimit is 0.
2. Add info about notify socks5 proxy support. [net.http.Transport](https://pkg.go.dev/net/http#Transport) supports both http and socks5 proxy. Tested. Really works.

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks for your contribution @AaronChen0 !

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Comment by dwisiswant0** [comment]
Could you please create the issue first, @AaronChen0?

File: internal/runner/runner.go [hunk 1]
```diff
@@ -80,6 +80,8 @@ func (r *Runner) Run() error {
 
 	if r.options.RateLimit > 0 {
 		http.DefaultClient.Transport = utils.NewThrottledTransport(time.Second, r.options.RateLimit, defaultTransport)
+	} else {
+		http.DefaultClient.Transport = defaultTransport
```
Comment (dwisiswant0) [inline internal/runner/runner.go:84]: I think we should avoid unnecessary nesting to make things clearer and potential for slightly better perf.

```go
	http.DefaultClient.Transport = defaultTransport
	if r.options.RateLimit > 0 {
		http.DefaultClient.Transport = utils.NewThrottledTransport(time.Second, r.options.RateLimit, defaultTransport)
	}
```

**Review by dwisiswant0 — CHANGES_REQUESTED** [review]

**Comment by AaronChen0** [comment]
Changes made. @dwisiswant0

**Review by dwisiswant0 — APPROVED** [review]
LGTM.

**Review by ehsandeep — APPROVED** [review]

**Comment by AaronChen0** [comment]
The failed check is irrelevant to this pull request.

Switching branch from `main` to `dev` introduced a commit not by me. Is this a concern when later `dev` branch merges back to `main` branch?

**Comment by dwisiswant0** [comment]
@AaronChen0 - you should rebase your branch.

**Comment by AaronChen0** [comment]
@dwisiswant0.  Rebase done.

**Review by dwisiswant0 — APPROVED** [review]
